/*
 * SRM-CAM photo relay — a Cloudflare Worker (free tier).
 *
 * Lets a phone hand a board photo to the app when the wifi blocks
 * device-to-device traffic (eduroam client isolation): both sides talk
 * to this worker instead of to each other, so the PC is never exposed.
 *
 *   GET  /u/<token>   the phone's take-photo page (QR target)
 *   POST /p/<token>   the phone uploads the photo (raw body)
 *   GET  /f/<token>   the app polls; 404 until the photo is there,
 *                     then the bytes ONCE (deleted on fetch)
 *
 * The <token> is a long random ID generated by the app per session —
 * unguessable, single-use, and every stored photo expires after 10
 * minutes regardless. Storage: Workers KV (binding: PHOTOS).
 *
 * Deploy (one-time, ~5 minutes — see relay/README.md):
 *   npx wrangler kv namespace create PHOTOS   # paste id into wrangler.toml
 *   npx wrangler deploy
 */

const MAX_BYTES = 20 * 1024 * 1024;
const TTL_S = 600;

const PAGE = `<!DOCTYPE html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>SRM-CAM photo</title><style>
body{background:#171b22;color:#d7dde6;font-family:system-ui,sans-serif;
 display:flex;flex-direction:column;align-items:center;justify-content:center;
 min-height:100vh;margin:0;gap:24px;text-align:center}
h1{font-size:1.2rem;margin:0}
label{background:#d8893c;color:#16120c;font-weight:700;font-size:1.2rem;
 padding:20px 44px;border-radius:14px;cursor:pointer}
input{display:none}#st{color:#98a2b3;min-height:1.4em;padding:0 20px}
.ok{color:#4fc07a;font-weight:700}.err{color:#e06555}</style></head><body>
<h1>SRM-CAM &mdash; board photo</h1>
<label for="f">&#128247; Take photo</label>
<input id="f" type="file" accept="image/*" capture="environment">
<div id="st">Straight down, even light, no glare.</div>
<script>
const f=document.getElementById('f'),st=document.getElementById('st');
f.addEventListener('change',async()=>{
 if(!f.files.length)return;
 st.textContent='Uploading\\u2026';st.className='';
 try{
  const r=await fetch('%POST%',{method:'POST',body:f.files[0],
   headers:{'Content-Type':f.files[0].type||'image/jpeg'}});
  if(r.ok){st.textContent='\\u2713 Received \\u2014 continue on the PC';
   st.className='ok';document.querySelector('label').style.display='none';}
  else{st.textContent='Upload failed ('+r.status+') \\u2014 try again';
   st.className='err';}
 }catch(e){st.textContent='Upload failed \\u2014 check the connection';
  st.className='err';}
});
</script></body></html>`;

export default {
  async fetch(req, env) {
    const m = new URL(req.url).pathname.match(
      /^\/(u|p|f)\/([A-Za-z0-9_-]{12,64})$/);
    if (!m) return new Response("not found", { status: 404 });
    const [, kind, id] = m;
    const key = "photo:" + id;

    if (kind === "u" && req.method === "GET") {
      return new Response(PAGE.replaceAll("%POST%", "/p/" + id), {
        headers: { "content-type": "text/html; charset=utf-8" },
      });
    }
    if (kind === "p" && req.method === "POST") {
      const buf = await req.arrayBuffer();
      if (buf.byteLength < 100 || buf.byteLength > MAX_BYTES)
        return new Response("bad size", { status: 413 });
      const ctype = (req.headers.get("content-type") || "image/jpeg")
        .split(";")[0];
      await env.PHOTOS.put(key, buf, {
        expirationTtl: TTL_S, metadata: { ctype },
      });
      return new Response("ok");
    }
    if (kind === "f" && req.method === "GET") {
      const { value, metadata } = await env.PHOTOS.getWithMetadata(key, {
        type: "arrayBuffer",
      });
      if (!value) return new Response("pending", { status: 404 });
      await env.PHOTOS.delete(key);                 // one-shot hand-off
      return new Response(value, {
        headers: {
          "content-type": (metadata && metadata.ctype) || "image/jpeg",
        },
      });
    }
    return new Response("not found", { status: 404 });
  },
};
